FROM node:20-alpine
WORKDIR /app
COPY services/gateway/package.json /app/package.json
COPY services/gateway/pnpm-lock.yaml* /app/pnpm-lock.yaml
RUN corepack enable || true
RUN pnpm i
COPY services/gateway .
ENV NODE_ENV=development
EXPOSE 4000
CMD ["sh", "-c", "npx chokidar-cli package.json pnpm-lock.yaml -c 'echo Installing... && pnpm install' & pnpm dev"]

